# Generated by Django 4.1.2 on 2022-11-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_personfilmwork_film_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'actor'), ('director', 'director'), ('writer', 'writer')], null=True, verbose_name='role'),
        ),
    ]
